{% set name = "attrs-strict" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/attrs_strict-{{ version }}.tar.gz
  sha256: e704863620146c5f2a8b601cd4574d148913db26fc0636f941fe4212e425eafe

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - setuptools >=67.6.1
    - setuptools-scm >=7.1
    - pip
  run:
    - python
    - attrs >=22.2
    - typing-extensions >=4.5  # [py<38]

test:
  imports:
    - attrs_strict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bloomberg/attrs-strict
  summary: Runtime validators for attrs
  dev_url: https://github.com/bloomberg/attrs-strict
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thht
